version: '3.6'
services:
  telegraf:
    image: telegraf:1.25-alpine
    container_name: telegraf
    build:
      context: telegraf
      dockerfile: Dockerfile
    user: "telegraf:20"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /Users/daghan/.docker/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125'
    networks:
      - influx-net

  influxdb:
    image: influxdb:2.6-alpine
    container_name: influxdb
    build:
      context: influxdb
      dockerfile: Dockerfile
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - influx-net

  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - influx-net

networks:
  influx-net:
volumes:
  grafana_data:
  influxdb_data: